name: Deploy Backend to Render

on:
  push:
    branches:
      - main   # trigger ทุกครั้งที่ push ไป branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. ดึงโค้ดจาก repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. ติดตั้ง Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. ติดตั้ง dependencies
      - name: Install dependencies
        run: npm install
        working-directory: backend

      # 4. Deploy ไป Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
